### ISSUE TITLE
WIP: Add Scheduling

### ISSUE THREAD

**Issue by BrianGreenhill** [BrianGreenhill/blackbox#3]
In order to get regular feedback about a site's availability, site checks should be schedulable through a simple interface.

I thought of some possible approaches for implementing this feature:
 
1. pass a schedule as a flag to the command `--schedule cronformat`
2. use a configuration file to define various sites and their schedules:
```yaml
checks:
  - site:
       name: sitename
       url: siteurl
       frequency: 1m
```
3. add a configuration dashboard with a list of sites and their schedules
4. expose an API endpoint that accepts a `ScheduleSiteCheckRequest` containing: `name, url, frequency` in the body and create the site check centrally
